add file storage
k-morozov/click pull request #9
Opened 2023-07-31 18:21 UTC by k-morozov

2023-08-02 16:44 UTC, kilchik requested changes
Нужно поправить работу с ошибками:
- все фатальные ошибки при старте должны приводить к записи в лог и завершению приложения (возможно с кодом отличным от 0)
- все критические ошибки в хэндлерах должны доходить до пользователя как внутренние ошибки сервера

2023-08-02 16:44 UTC, kilchik commented on internal/storage/file_manager.go
> +		panic("broken storage file")
Паники из произвольного места в коде сильно ухудшают поддерживаемость проекта. Тут следует вернуть из конструктора ошибку, а в месте вызова сделать запись в лог и корректно завершить выполнение программы

2023-08-02 16:44 UTC, kilchik commented on internal/storage/simple_memory.go
>  type SimpleMemoryStorage struct {
Кажется, уже некорректно называть это хранилище Memory с учетом того, что тут может происходить запись в файл

2023-08-02 16:44 UTC, kilchik commented on internal/storage/simple_memory.go
> +	if res, err := logic.Decompress([]byte(originalURL)); err == nil {
Тут что-то не так. А если вернулась ошибка? Ошибок Decompress может вернуть несколько, во всех случаях идем дальше?

2023-08-02 16:44 UTC, kilchik commented on internal/handlers/make_shorten.go
> +		http.Error(rw, "not all bytes", http.StatusBadRequest)
Но ведь это не ошибка клиента - это внутренняя ошибка сервера

2023-08-02 16:44 UTC, kilchik commented on internal/storage/simple_memory.go
> +		s.fileManager.Write(Event{
А если произошла ошибка при записи? Клиент получит 200, а данные будут в неконсистентном состоянии. Ошибку следует обрабатывать всегда, Go навязывает явную обработку ошибку в том месте, где она произошла. В данном случае клиент обязательно должен получить серверную ошибку, иначе будет считать, что данные были сохранены

2023-08-02 16:44 UTC, kilchik commented on internal/logic/common.go
> +package logic
Лучше именовать пакеты так, чтобы было понятно, за что отвечает код в них. В данном случае logic такое же неочевидное название, как utils/misc/common/helpers. Если это пакет, отвечающий за компрессию, предлагаю его переименовать соответствующе

2023-08-02 16:44 UTC, kilchik commented on internal/storage/simple_memory.go
> +			log.Printf("[debug] error load from disk: %s\n", err)
Если произошла ошибка при чтении из файла, то это critical, об этом следует оповестить пользователя логом уровня error и не дать сервису возможности стартовать, пробросив ошибку до main

2023-08-03 14:32 UTC, k-morozov commented on internal/storage/simple_memory.go
>  type SimpleMemoryStorage struct {
ok

2023-08-03 14:32 UTC, k-morozov commented on internal/storage/simple_memory.go
> +	if res, err := logic.Decompress([]byte(originalURL)); err == nil {
воркраунд на сломанный тест в CI - обсуждение в чатике.

2023-08-04 15:24 UTC, k-morozov commented on internal/logic/common.go
> +package logic
переименовал

2023-08-06 17:20 UTC, kilchik approved these changes

2023-08-06 19:06 UTC, merged